### ISSUE TITLE
Hi, when I try to install scs with gpu, it comes with the following error: 

### ISSUE THREAD

**Issue by QiuCB** [bodono/scs-python#71]
**Please read this first**

If you are have a problem that SCS struggles with you can pass a string to the
`write_data_filename` argument and SCS will dump a file containing the problem
to disk. Zip the file and send it to us or attach it to this bug report for easy
reproduction of the issue.

A common cause of issues is not linking BLAS/LAPACK libraries correctly. 
SCS relies on Numpy to tell it where these libraries are on your system, using
the `get_info` commands:
```python
from numpy.distutils.system_info import get_info
print(get_info("blas_opt"))  # best blas install
print(get_info("lapack_opt"))  # best lapack install
print(get_info("blas"))  # fall back blas install
print(get_info("lapack"))  # fall back lapack install
```
If you are having this issue please search for resources on installing and
linking these libraries in python first. Also please make sure that the output
of the `get_info` commands above make sense for your system, ie, that the
`library_dirs` they return actually exist. You can try openblas if you need a
BLAS library.

## Specifications
- OS:
- SCS version:
- Python version:
- Numpy version:
- Scipy version:
- Output of `get_info` print commands as above (if applicable):
- Data file location dumped with `write_data_filename` (if applicable):

## Description
A clear and concise description of the problem.

## How to reproduce
Ideally a minimal snippet of code that reproduces the problem if possible.

## Additional information
Extra context.

## Output
Entire SCS output including the entire stack trace (if applicable).

**Comment by bodono** [comment]
What version of Cuda / CUsparse are you using? This looks like you're probably using an older version than SCS is assuming.

**Comment by QiuCB** [comment]
> What version of Cuda / CUsparse are you using? This looks like you're probably using an older version than SCS is assuming.

Thank you for your reply. My CUDA version is 10.2.  And if it is a version problem, can I get an earlier version of SCS? Or can I only solve it by updating CUDA?

**Comment by bodono** [comment]
I'm not sure what the earliest version of CuSparse where those functions appeared, but they are in version 12.2: https://docs.nvidia.com/cuda/cusparse/

I would recommend updating CuSparse over using an old version of SCS. Alternately you can use the MKL version of SCS, which is trypically faster than the GPU version anyway.

**Comment by QiuCB** [comment]
> I'm not sure what the earliest version of CuSparse where those functions appeared, but they are in version 12.2: https://docs.nvidia.com/cuda/cusparse/
> 
> I would recommend updating CuSparse over using an old version of SCS. Alternately you can use the MKL version of SCS, which is trypically faster than the GPU version anyway.

Okay, I'll try the MKL version of SCS first, thanks again!

**Comment by QiuCB** [comment]
> I'm not sure what the earliest version of CuSparse where those functions appeared, but they are in version 12.2: https://docs.nvidia.com/cuda/cusparse/
> 
> I would recommend updating CuSparse over using an old version of SCS. Alternately you can use the MKL version of SCS, which is trypically faster than the GPU version anyway.

====================================

(GPU version) Hello, I upgraded my CUDA but this error seems to still persist and there are many "unknown type name" errors.

```Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, gpu_atrans=True, int32=False, scs=True)
running install
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing scs.egg-info/PKG-INFO
writing dependency_links to scs.egg-info/dependency_links.txt
writing requirements to scs.egg-info/requires.txt
writing top-level names to scs.egg-info/top_level.txt
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/distutils/system_info.py:2026: UserWarning: 
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
{'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'libraries': ['cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['/home/ubuntu/anaconda3/envs/test2/lib'], 'include_dirs': ['/home/ubuntu/anaconda3/envs/test2/include'], 'language': 'c'}
{'libraries': ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['/home/ubuntu/anaconda3/envs/test2/lib'], 'language': 'c', 'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'include_dirs': ['/home/ubuntu/anaconda3/envs/test2/include']}
warning: no directories found matching 'scs'
warning: no directories found matching 'scs/src'
warning: no directories found matching 'scs/test'
warning: no directories found matching 'scs/test/problems'
warning: no directories found matching 'scs/include'
warning: no directories found matching 'scs/linsys'
warning: no directories found matching 'scs/linsys/cpu'
warning: no directories found matching 'scs/linsys/cpu/direct'
warning: no directories found matching 'scs/linsys/cpu/indirect'
warning: no directories found matching 'scs/linsys/gpu'
warning: no directories found matching 'scs/linsys/gpu/indirect'
warning: no directories found matching 'scs/linsys/external'
warning: no directories found matching 'scs/linsys/external/amd'
warning: no directories found matching 'scs/linsys/external/qdldl'
src/scspy.c:16:10: fatal error: glbopts.h: No such file or directory
 #include "glbopts.h"           /* Constants and *alloc */
          ^~~~~~~~~~~
compilation terminated.
error: Command "gcc -pthread -B /home/ubuntu/anaconda3/envs/test2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPYTHON -DCTRLC=1 -DDLONG=1 -DUSE_LAPACK -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -I/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/core/include -I/home/ubuntu/anaconda3/envs/test2/include -I/home/ubuntu/anaconda3/envs/test2/include -I/home/ubuntu/anaconda3/envs/test2/include/python3.7m -c src/scspy.c -o build/temp.linux-x86_64-cpython-37/src/scspy.o -O3" failed with exit status 1
(test2) ubuntu@LXCqiuchengbo2:~/test0330/scs_test/scs-python-3.2.0$ python setup.py install --scs --gpu
Namespace(blas64=False, extraverbose=False, float32=False, gpu=True, gpu_atrans=True, int32=False, scs=True)
running install
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing scs.egg-info/PKG-INFO
writing dependency_links to scs.egg-info/dependency_links.txt
writing requirements to scs.egg-info/requires.txt
writing top-level names to scs.egg-info/top_level.txt
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/distutils/system_info.py:2026: UserWarning: 
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
{'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'libraries': ['cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['/home/ubuntu/anaconda3/envs/test2/lib'], 'include_dirs': ['/home/ubuntu/anaconda3/envs/test2/include'], 'language': 'c'}
{'libraries': ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['/home/ubuntu/anaconda3/envs/test2/lib'], 'language': 'c', 'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'include_dirs': ['/home/ubuntu/anaconda3/envs/test2/include']}
warning: no directories found matching 'scs'
warning: no directories found matching 'scs/src'
warning: no directories found matching 'scs/test'
warning: no directories found matching 'scs/test/problems'
warning: no directories found matching 'scs/include'
warning: no directories found matching 'scs/linsys'
warning: no directories found matching 'scs/linsys/cpu'
warning: no directories found matching 'scs/linsys/cpu/direct'
warning: no directories found matching 'scs/linsys/cpu/indirect'
warning: no directories found matching 'scs/linsys/gpu'
warning: no directories found matching 'scs/linsys/gpu/indirect'
warning: no directories found matching 'scs/linsys/external'
warning: no directories found matching 'scs/linsys/external/amd'
warning: no directories found matching 'scs/linsys/external/qdldl'
src/scspy.c:16:10: fatal error: glbopts.h: No such file or directory
 #include "glbopts.h"           /* Constants and *alloc */
          ^~~~~~~~~~~
compilation terminated.
error: Command "gcc -pthread -B /home/ubuntu/anaconda3/envs/test2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPYTHON -DCTRLC=1 -DUSE_LAPACK -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -I/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/core/include -I/home/ubuntu/anaconda3/envs/test2/include -I/home/ubuntu/anaconda3/envs/test2/include -I/home/ubuntu/anaconda3/envs/test2/include/python3.7m -c src/scspy.c -o build/temp.linux-x86_64-cpython-37/src/scspy.o -O3" failed with exit status 1```

~~~~~~~~~~~~~

(MKL version) In addition, when I installed the MKL version, I also got an error, o(╥﹏╥)o

```Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, gpu_atrans=True, int32=False, scs=True)
running install
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing scs.egg-info/PKG-INFO
writing dependency_links to scs.egg-info/dependency_links.txt
writing requirements to scs.egg-info/requires.txt
writing top-level names to scs.egg-info/top_level.txt
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/distutils/system_info.py:2026: UserWarning: 
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
{'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'libraries': ['cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['/home/ubuntu/anaconda3/envs/test2/lib'], 'include_dirs': ['/home/ubuntu/anaconda3/envs/test2/include'], 'language': 'c'}
{'libraries': ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['/home/ubuntu/anaconda3/envs/test2/lib'], 'language': 'c', 'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'include_dirs': ['/home/ubuntu/anaconda3/envs/test2/include']}
warning: no directories found matching 'scs'
warning: no directories found matching 'scs/src'
warning: no directories found matching 'scs/test'
warning: no directories found matching 'scs/test/problems'
warning: no directories found matching 'scs/include'
warning: no directories found matching 'scs/linsys'
warning: no directories found matching 'scs/linsys/cpu'
warning: no directories found matching 'scs/linsys/cpu/direct'
warning: no directories found matching 'scs/linsys/cpu/indirect'
warning: no directories found matching 'scs/linsys/gpu'
warning: no directories found matching 'scs/linsys/gpu/indirect'
warning: no directories found matching 'scs/linsys/external'
warning: no directories found matching 'scs/linsys/external/amd'
warning: no directories found matching 'scs/linsys/external/qdldl'
src/scspy.c:16:10: fatal error: glbopts.h: No such file or directory
 #include "glbopts.h"           /* Constants and *alloc */
          ^~~~~~~~~~~
compilation terminated.
error: Command "gcc -pthread -B /home/ubuntu/anaconda3/envs/test2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPYTHON -DCTRLC=1 -DDLONG=1 -DUSE_LAPACK -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -I/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/core/include -I/home/ubuntu/anaconda3/envs/test2/include -I/home/ubuntu/anaconda3/envs/test2/include -I/home/ubuntu/anaconda3/envs/test2/include/python3.7m -c src/scspy.c -o build/temp.linux-x86_64-cpython-37/src/scspy.o -O3" failed with exit status 1```

**Comment by QiuCB** [comment]
(MKL version) In addition, when I installed the MKL version, I also got some error, o(╥﹏╥)o


```Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, gpu_atrans=True, int32=False, scs=True)
running install
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing scs.egg-info/PKG-INFO
writing dependency_links to scs.egg-info/dependency_links.txt
writing requirements to scs.egg-info/requires.txt
writing top-level names to scs.egg-info/top_level.txt
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/ubuntu/anaconda3/envs/test2/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ubuntu/anaconda3/envs/test2/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/distutils/system_info.py:2026: UserWarning: 
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
{'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'libraries': ['cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['/home/ubuntu/anaconda3/envs/test2/lib'], 'include_dirs': ['/home/ubuntu/anaconda3/envs/test2/include'], 'language': 'c'}
{'libraries': ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas'], 'library_dirs': ['/home/ubuntu/anaconda3/envs/test2/lib'], 'language': 'c', 'define_macros': [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)], 'include_dirs': ['/home/ubuntu/anaconda3/envs/test2/include']}
warning: no directories found matching 'scs'
warning: no directories found matching 'scs/src'
warning: no directories found matching 'scs/test'
warning: no directories found matching 'scs/test/problems'
warning: no directories found matching 'scs/include'
warning: no directories found matching 'scs/linsys'
warning: no directories found matching 'scs/linsys/cpu'
warning: no directories found matching 'scs/linsys/cpu/direct'
warning: no directories found matching 'scs/linsys/cpu/indirect'
warning: no directories found matching 'scs/linsys/gpu'
warning: no directories found matching 'scs/linsys/gpu/indirect'
warning: no directories found matching 'scs/linsys/external'
warning: no directories found matching 'scs/linsys/external/amd'
warning: no directories found matching 'scs/linsys/external/qdldl'
src/scspy.c:16:10: fatal error: glbopts.h: No such file or directory
 #include "glbopts.h"           /* Constants and *alloc */
          ^~~~~~~~~~~
compilation terminated.
error: Command "gcc -pthread -B /home/ubuntu/anaconda3/envs/test2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPYTHON -DCTRLC=1 -DDLONG=1 -DUSE_LAPACK -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -I/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/numpy/core/include -I/home/ubuntu/anaconda3/envs/test2/include -I/home/ubuntu/anaconda3/envs/test2/include -I/home/ubuntu/anaconda3/envs/test2/include/python3.7m -c src/scspy.c -o build/temp.linux-x86_64-cpython-37/src/scspy.o -O3" failed with exit status 1```

**Comment by QiuCB** [comment]
> I'm not sure what the earliest version of CuSparse where those functions appeared, but they are in version 12.2: https://docs.nvidia.com/cuda/cusparse/
> 
> I would recommend updating CuSparse over using an old version of SCS. Alternately you can use the MKL version of SCS, which is trypically faster than the GPU version anyway.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Hello, I seem to have finally installed scs-gpu. And the version of scs is 3.2.0.

But there are some problems when using it. My test code is as follows:

```
import cvxpy as cp
import numpy as np

# Generate random SDP problem
n = 100
np.random.seed(1)
A = np.random.randn(n, n)
A = 0.5 * (A + A.T)
X = cp.Variable((n, n), PSD=True)
obj = cp.Maximize(cp.trace(A @ X))
constraints = [X >= 0, cp.trace(X) == 1]
prob = cp.Problem(obj, constraints)

# Solve problem on GPU
prob.solve(solver=cp.SCS, gpu=True, use_indirect=True)

# Print solution
print("Optimal value: ", prob.value)
print("Solution: ")
print(X.value)
```

And the error reported is as follows:
```cudaError: 803 (100 indicates no device)
ERROR: init_lin_sys_work failure
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    prob.solve(solver=cp.SCS, gpu=True, use_indirect=True)
  File "/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 1017, in _solve
    self, data, warm_start, verbose, kwargs)
  File "/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 362, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 329, in solve_via_data
    results, status = solve(solver_opts)
  File "/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 324, in solve
    _results = scs.solve(args, cones, verbose=verbose, **_solver_opts)
  File "/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/scs-3.2.0-py3.7-linux-x86_64.egg/scs/__init__.py", line 166, in solve
    solver = SCS(data, cone, **settings)
  File "/home/ubuntu/anaconda3/envs/test2/lib/python3.7/site-packages/scs-3.2.0-py3.7-linux-x86_64.egg/scs/__init__.py", line 129, in __init__
    **self._settings
ValueError: ScsWork allocation error!```

I'm wondering if I haven't found the right way to use the scs-gpu yet
