### ISSUE TITLE
MKL version

### ISSUE THREAD

**Issue by QiuCB** [bodono/scs-python#72]
# scs-mkl version

I tried to install the scs-mkl version with `python setup.py install --scs --mkl`, and the following prompt appeared. I understood that the installation should be successful.

```
Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, gpu_atrans=True, int32=False, scs=True)
/home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running install
/home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing scs.egg-info/PKG-INFO
writing dependency_links to scs.egg-info/dependency_links.txt
writing requirements to scs.egg-info/requires.txt
writing top-level names to scs.egg-info/top_level.txt
setup.py:84: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 


  from numpy.distutils.system_info import get_info
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
{'libraries': ['openblas', 'openblas'], 'library_dirs': ['/usr/lib/x86_64-linux-gnu'], 'language': 'c', 'define_macros': [('HAVE_CBLAS', None)]}
{'libraries': ['openblas', 'openblas'], 'library_dirs': ['/usr/lib/x86_64-linux-gnu'], 'language': 'c', 'define_macros': [('HAVE_CBLAS', None)]}
Adding scs 3.2.0 to easy-install.pth file

Installed /home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages/scs-3.2.0-py3.8-linux-x86_64.egg
Processing dependencies for scs==3.2.0
Searching for scipy==1.10.1
Best match: scipy 1.10.1
Adding scipy 1.10.1 to easy-install.pth file

Using /home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages
Searching for numpy==1.24.4
Best match: numpy 1.24.4
Adding numpy 1.24.4 to easy-install.pth file
Installing f2py script to /home/ubuntu/anaconda3/envs/test3/bin
Installing f2py3 script to /home/ubuntu/anaconda3/envs/test3/bin
Installing f2py3.8 script to /home/ubuntu/anaconda3/envs/test3/bin

Using /home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages
Finished processing dependencies for scs==3.2.0
```

But when I ran the following code and tried to verify whether it could be solved using scs-mkl, 
```
import cvxpy as cp
import numpy as np

# Generate random SDP problem
n = 100
# np.random.seed(1)
A = np.random.randn(n, n)
A = 0.5 * (A + A.T)
X = cp.Variable((n, n), PSD=True)
obj = cp.Maximize(cp.trace(A @ X))
constraints = [X >= 0, cp.trace(X) == 1]
prob = cp.Problem(obj, constraints)

# Solve problem on MKL
params = {"verbose": True, "eps_abs": 1e-5, "eps_rel": 1e-5, "eps_infeas": 1e-5}
prob.solve(solver=cp.SCS, mkl=True, **params)

# Print solution
print("Optimal value: ", prob.value)
print("Solution: ")
print(X.value)
```

the following problem occurred. I tried to solve it but failed:

```
===============================================================================
                                     CVXPY                                     
                                     v1.4.0                                    
===============================================================================
(CVXPY) Oct 11 07:31:19 AM: Your problem has 10000 variables, 2 constraints, and 0 parameters.
(CVXPY) Oct 11 07:31:19 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Oct 11 07:31:19 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Oct 11 07:31:19 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Oct 11 07:31:19 AM: Your problem is compiled with the CPP canonicalization backend.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Oct 11 07:31:19 AM: Compiling problem (target solver=SCS).
(CVXPY) Oct 11 07:31:19 AM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> SCS
(CVXPY) Oct 11 07:31:19 AM: Applying reduction FlipObjective
(CVXPY) Oct 11 07:31:19 AM: Applying reduction Dcp2Cone
(CVXPY) Oct 11 07:31:19 AM: Applying reduction CvxAttr2Constr
(CVXPY) Oct 11 07:31:19 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Oct 11 07:31:19 AM: Applying reduction SCS
(CVXPY) Oct 11 07:31:19 AM: Finished problem compilation (took 1.943e-01 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Oct 11 07:31:19 AM: Invoking solver SCS  to obtain a solution.
Traceback (most recent call last):
  File "test.py", line 103, in <module>
    prob.solve(solver=cp.SCS, mkl=True, **params)
  File "/home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 503, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 1077, in _solve
    solution = solving_chain.solve_via_data(
  File "/home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 453, in solve_via_data
    return self.solver.solve_via_data(data, warm_start, verbose,
  File "/home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 342, in solve_via_data
    results, status = solve(solver_opts)
  File "/home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 337, in solve
    _results = scs.solve(args, cones, verbose=verbose, **_solver_opts)
  File "/home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages/scs-3.2.0-py3.8-linux-x86_64.egg/scs/__init__.py", line 166, in solve
    solver = SCS(data, cone, **settings)
  File "/home/ubuntu/anaconda3/envs/test3/lib/python3.8/site-packages/scs-3.2.0-py3.8-linux-x86_64.egg/scs/__init__.py", line 118, in __init__
    self._solver = _scs.SCS(
ValueError: Error parsing inputs
```

After installing scs-mkl, I ran pytest for verification, and both passed.
```
================================================= test session starts =================================================
platform linux -- Python 3.8.18, pytest-7.4.2, pluggy-1.3.0 -- /home/ubuntu/anaconda3/envs/test3/bin/python3.8
cachedir: .pytest_cache
rootdir: /home/ubuntu/test0330/scs_test/scs-python-3.2.0
collected 24 items                                                                                                    

test/test_scs_basic.py::test_problems[cone0-False-1] PASSED                                                     [  4%]
test/test_scs_basic.py::test_problems[cone1-True-1] PASSED                                                      [  8%]
test/test_scs_basic.py::test_problems[cone2-False-0.5] PASSED                                                   [ 12%]
test/test_scs_basic.py::test_problems[cone3-True-0.5] PASSED                                                    [ 16%]
test/test_scs_basic.py::test_failures PASSED                                                                    [ 20%]
test/test_scs_object.py::test_update[False] PASSED                                                              [ 25%]
test/test_scs_object.py::test_update[True] PASSED                                                               [ 29%]
test/test_scs_object.py::test_warm_start[False] PASSED                                                          [ 33%]
test/test_scs_object.py::test_warm_start[True] PASSED                                                           [ 37%]
test/test_scs_rand.py::test_feasible[False] PASSED                                                              [ 41%]
test/test_scs_rand.py::test_feasible[True] PASSED                                                               [ 45%]
test/test_scs_rand.py::test_infeasible[False] PASSED                                                            [ 50%]
test/test_scs_rand.py::test_infeasible[True] PASSED                                                             [ 54%]
test/test_scs_rand.py::test_unbounded[False] PASSED                                                             [ 58%]
test/test_scs_sdp.py::test_feasible[False] PASSED                                                               [ 62%]
test/test_scs_sdp.py::test_feasible[True] PASSED                                                                [ 66%]
test/test_scs_sdp.py::test_infeasible[False] PASSED                                                             [ 70%]
test/test_scs_sdp.py::test_infeasible[True] PASSED                                                              [ 75%]
test/test_scs_sdp.py::test_unbounded[False] PASSED                                                              [ 79%]
test/test_solve_random_cone_prob.py::test_solve_feasible[False-False] PASSED                                    [ 83%]
test/test_solve_random_cone_prob.py::test_solve_feasible[True-False] PASSED                                     [ 87%]
test/test_solve_random_cone_prob.py::test_solve_infeasible[False-False] PASSED                                  [ 91%]
test/test_solve_random_cone_prob.py::test_solve_infeasible[True-False] PASSED                                   [ 95%]
test/test_solve_random_cone_prob.py::test_solve_unbounded[False-False] PASSED                                   [100%]

================================================= 24 passed in 12.19s =================================================
```

**Comment by bodono** [comment]
Hi @QiuCB , sorry for the delay in responding. Did you manage to get this to work?

**Comment by QiuCB** [comment]
> Hi @QiuCB , sorry for the delay in responding. Did you manage to get this to work?


Thanks for your reply.

I can currently use the MKL version successfully, but I would like to know what advantages the mkl version has compared to the original version (i.e. mkl is false), and will it speed up the sparse SDP problem? Where can I find the corresponding answer?

P.S.  Unfortunately, my GPU version still didn't work. cry...

**Comment by QiuCB** [comment]
@bodono, hi, 
In the example of pytest you gave, I see that the template using the mkl version is:
```
...
solver = scs.SCS(data, K, mkl=True, **params)
sol = solver.solve()
...
```

But I want to use scs as the solver in cvxpy, can I use the MKL version of scs with the following method:
```
# Define variables for the sparse SDP problem
X = cp.Variable((n, n), symmetric=True)

constraints = [X >> 0]

for i, j in indices:
    constraints.append(X[i, j] == sparse_matrix[i, j])

# Define objective function
objective = cp.Minimize(cp.trace(X))  # 最小化trace(X)

prob = cp.Problem(objective, constraints)
prob.solve()

# Solve problem on MKL
params = {"verbose": verbose, "max_iters": 10000}
prob.solve(solver=cp.SCS, mkl=True, **params)
```

Does this mean that I am using the MKL version of the scs solver?

**Comment by bodono** [comment]
You should be, if you pass in 'verbose=True' you should be able to see MKL in the linear system description in the SCS header.

**Comment by bodono** [comment]
> I can currently use the MKL version successfully, but I would like to know what advantages the mkl version has compared to the original version (i.e. mkl is false), and will it speed up the sparse SDP problem? Where can I find the corresponding answer? (Because I noticed that the CPU utilization when running these two methods is similar.)


The MKL version should be much faster, make sure you are enabling multi-threading with OMP_NUM_THREADS='some_number' and / or MKL_NUM_THREADS='some_number' before starting the python process.

**Comment by QiuCB** [comment]
> > I can currently use the MKL version successfully, but I would like to know what advantages the mkl version has compared to the original version (i.e. mkl is false), and will it speed up the sparse SDP problem? Where can I find the corresponding answer? (Because I noticed that the CPU utilization when running these two methods is similar.)
> 
> The MKL version should be much faster, make sure you are enabling multi-threading with OMP_NUM_THREADS='some_number' and / or MKL_NUM_THREADS='some_number' before starting the python process.

Yes, I set the parameters OMP_NUM_THREADS and MKL_NUM_THREADS to 32, and then ran the python process with MKL=True and False respectively.
But when I counted the time consumption, I found that the original program took less time than the MKL version. The following is the specific output.

## test python code:
```
@get_time
def test2(n, seed=1, version='mkl', verbose=True):
    np.random.seed(seed)
    # A = np.random.randn(n, n)
    # A = A.astype(np.float32)

    num_nonzero_elements = int(n*0.5)  # number of non-zero elements in the matrix
    indices = np.random.choice(range(n), size=(num_nonzero_elements, 2), replace=False)
    values = np.random.rand(num_nonzero_elements)
    sparse_matrix = np.zeros((n, n))
    for idx, (i, j) in enumerate(indices):
        sparse_matrix[i, j] = values[idx]

    # Define variables for the sparse SDP problem
    X = cp.Variable((n, n), symmetric=True)

    constraints = [X >> 0] 
    for i, j in indices:
        constraints.append(X[i, j] == sparse_matrix[i, j]) 

    objective = cp.Minimize(cp.trace(X))  # 最小化trace(X)
    prob = cp.Problem(objective, constraints)

    if version.lower() == 'gpu':
        # Solve problem on GPU
        prob.solve(solver=cp.SCS, gpu=True, use_indirect=True, verbose=verbose, max_iters=10000)
        prob.solve()
    elif version.lower() == 'mkl':
        # Solve problem on MKL
        params = {"verbose": verbose, "max_iters": 10000}
        prob.solve(solver=cp.SCS, mkl=True, **params)
    else:
        params = {"verbose": verbose, "max_iters": 10000}
        prob.solve(solver=cp.SCS, **params)

    return prob.value, X.value
```

## MKL=False, output log
```
===============================================================================
                                     CVXPY                                     
                                     v1.2.2                                    
===============================================================================
(CVXPY) Oct 19 02:45:31 AM: Your problem has 1000000 variables, 501 constraints, and 0 parameters.
(CVXPY) Oct 19 02:45:31 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Oct 19 02:45:31 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Oct 19 02:45:31 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Oct 19 02:45:31 AM: Compiling problem (target solver=SCS).
(CVXPY) Oct 19 02:45:31 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> SCS
(CVXPY) Oct 19 02:45:31 AM: Applying reduction Dcp2Cone
(CVXPY) Oct 19 02:45:31 AM: Applying reduction CvxAttr2Constr
(CVXPY) Oct 19 02:45:34 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Oct 19 02:47:24 AM: Applying reduction SCS
(CVXPY) Oct 19 02:47:25 AM: Finished problem compilation (took 1.141e+02 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Oct 19 02:47:25 AM: Invoking solver SCS  to obtain a solution.
------------------------------------------------------------------
               SCS v3.2.3 - Splitting Conic Solver
        (c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 500500, constraints m: 501000
cones:    z: primal zero / dual free vars: 500
          s: psd vars: 500500, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
          alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
          max_iters: 10000, normalize: 1, rho_x: 1.00e-06
          acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-amd-qdldl
          nnz(A): 501000, nnz(P): 0
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.83e+01  1.00e+00  2.83e+04 -1.41e+04  1.00e-01  1.64e+00 
   250| 1.12e-02  1.17e-03  1.46e-04  5.05e+02  1.30e+00  5.66e+01 
   300| 1.55e-06  2.61e-06  7.33e-08  5.05e+02  1.30e+00  6.58e+01 
------------------------------------------------------------------
status:  solved
timings: total: 6.58e+01s = setup: 1.38e+00s + solve: 6.44e+01s
         lin-sys: 5.73e+00s, cones: 5.51e+01s, accel: 8.36e-01s
------------------------------------------------------------------
objective = 504.542505
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) Oct 19 02:48:31 AM: Problem status: optimal
(CVXPY) Oct 19 02:48:31 AM: Optimal value: 5.045e+02
(CVXPY) Oct 19 02:48:31 AM: Compilation took 1.141e+02 seconds
(CVXPY) Oct 19 02:48:31 AM: Solver (including time spent in interface) took 6.583e+01 seconds
Time Consuming: 180.09661054611206 second
Optimal value:  504.5425047369855
```


## MKL version, output log
```
===============================================================================
                                     CVXPY                                     
                                     v1.2.2                                    
===============================================================================
(CVXPY) Oct 19 02:39:11 AM: Your problem has 1000000 variables, 501 constraints, and 0 parameters.
(CVXPY) Oct 19 02:39:11 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Oct 19 02:39:11 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Oct 19 02:39:11 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Oct 19 02:39:11 AM: Compiling problem (target solver=SCS).
(CVXPY) Oct 19 02:39:11 AM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> SCS
(CVXPY) Oct 19 02:39:11 AM: Applying reduction Dcp2Cone
(CVXPY) Oct 19 02:39:11 AM: Applying reduction CvxAttr2Constr
(CVXPY) Oct 19 02:39:14 AM: Applying reduction ConeMatrixStuffing
(CVXPY) Oct 19 02:41:05 AM: Applying reduction SCS
(CVXPY) Oct 19 02:41:06 AM: Finished problem compilation (took 1.146e+02 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Oct 19 02:41:06 AM: Invoking solver SCS  to obtain a solution.
------------------------------------------------------------------
               SCS v3.2.3 - Splitting Conic Solver
        (c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 500500, constraints m: 501000
cones:    z: primal zero / dual free vars: 500
          s: psd vars: 500500, ssize: 1
settings: eps_abs: 1.0e-05, eps_rel: 1.0e-05, eps_infeas: 1.0e-07
          alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
          max_iters: 10000, normalize: 1, rho_x: 1.00e-06
          acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct-mkl-pardiso
          nnz(A): 501000, nnz(P): 0
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.83e+01  1.00e+00  2.83e+04 -1.41e+04  1.00e-01  1.82e+02 
   250| 1.12e-02  1.17e-03  1.47e-04  5.05e+02  1.30e+00  2.35e+02 
   300| 1.55e-06  2.61e-06  2.17e-11  5.05e+02  1.30e+00  2.45e+02 
------------------------------------------------------------------
status:  solved
timings: total: 2.45e+02s = setup: 1.82e+02s + solve: 6.32e+01s
         lin-sys: 9.36e+00s, cones: 4.98e+01s, accel: 8.13e-01s
------------------------------------------------------------------
objective = 504.542505
------------------------------------------------------------------
-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) Oct 19 02:45:11 AM: Problem status: optimal
(CVXPY) Oct 19 02:45:11 AM: Optimal value: 5.045e+02
(CVXPY) Oct 19 02:45:11 AM: Compilation took 1.146e+02 seconds
(CVXPY) Oct 19 02:45:11 AM: Solver (including time spent in interface) took 2.449e+02 seconds
Time Consuming: 359.6494023799896 second
Optimal value:  504.5425046637163
```

**Comment by bodono** [comment]
Wow that's way slower, are you using an intel processor? What operating system are you using?

**Comment by QiuCB** [comment]
> Wow that's way slower, are you using an intel processor? What operating system are you using?

yes, my computer has two CPUs, both are Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz. And my OS is LINUX (Ubuntu 16.04)。
